services:
  jekyll:
    build: ./
    volumes:
      - ./:/srv/jekyll
    entrypoint: /bin/bash -c "chmod +x ./startup.sh && ./startup.sh ${MODE}"
    restart: "no"
    ports:
      - "4000:4000"
    environment:
      - JEKYLL_UID=33
      - JEKYLL_GID=33
